#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Gemeinsame Texte aller Katzenprofile. Katzennamen und Vereinsdaten bleiben unverändert."""

KATZE_COMMON_EN = {
    "Unser Ansatz": "Our approach",
    "Versorgungsroute": "Care route",
    "Transparenz": "Transparency",
    "Mithelfen": "Get involved",
    "Fördern": "Donate",
    "Katzen": "Cats",
    "sucht Zuhause": "looking for a home",
    "Name": "Name",
    "Geschlecht": "Sex",
    "Geboren": "Born",
    "Rasse": "Breed",
    "Aufenthaltsregion": "Region",
    "Geimpft": "Vaccinated",
    "Kastriert": "Neutered",
    "Grösse": "Size",
    "Status": "Status",
    "Gewünschte Haltungsform": "Preferred keeping",
    "FIV-/FeLV-Test": "FIV/FeLV test",
    "vor der Ausreise vorgesehen": "planned before departure",
    "Vermittlung über": "Rehoming via",
    "Medizinischer Stand": "Medical status",
    "Was gesichert ist": "What is confirmed",
    "Was noch aussteht": "What is still outstanding",
    "Bilder": "Images",
    "Verantwortlich für die Vermittlung": "Responsible for rehoming",
    "Bewerbungsformular": "Application form",
    "(öffnet in neuem Tab)": "(opens in a new tab)",
    "Vermittlungsverfahren": "Rehoming procedure",
    "Vereinsangaben": "Association details",
    "Registergericht: Amtsgericht Bochum": "Register court: Bochum Local Court",
    "Registernummer: VR 4939": "Register number: VR 4939",
    "deinem Leben": "your life",
    "passen?": "?",
    "Bewerbungsformular öffnen": "Open the application form",
    "Zurück zu allen Katzen": "Back to all cats",
    "Alle Katzen": "All cats",
    "© 2026 Margo Animal Care Initiative · Artemida, Griechenland":
        "© 2026 Margo Animal Care Initiative · Artemida, Greece",
    # wiederkehrende Zusätze
    "Vermittlungsverfahren ansehen": "View the rehoming procedure",
    "männlich": "male",
    "weiblich": "female",
    "Mischling": "mixed breed",
    "mittel": "medium",
    "klein": "small",
    "gross": "large",
}

KATZE_COMMON_EL = {
    "Unser Ansatz": "Η προσέγγισή μας",
    "Versorgungsroute": "Διαδρομή φροντίδας",
    "Transparenz": "Διαφάνεια",
    "Mithelfen": "Συμμετοχή",
    "Fördern": "Δωρεές",
    "Katzen": "Γάτες",
    "sucht Zuhause": "αναζητά σπίτι",
    "Name": "Όνομα",
    "Geschlecht": "Φύλο",
    "Geboren": "Γεννήθηκε",
    "Rasse": "Ράτσα",
    "Aufenthaltsregion": "Περιοχή",
    "Geimpft": "Εμβολιασμένη",
    "Kastriert": "Στειρωμένη",
    "Grösse": "Μέγεθος",
    "Status": "Κατάσταση",
    "Gewünschte Haltungsform": "Επιθυμητός τρόπος διαβίωσης",
    "FIV-/FeLV-Test": "Τεστ FIV/FeLV",
    "vor der Ausreise vorgesehen": "προβλέπεται πριν την αναχώρηση",
    "Vermittlung über": "Υιοθεσία μέσω",
    "Medizinischer Stand": "Ιατρική κατάσταση",
    "Was gesichert ist": "Τι είναι βέβαιο",
    "Was noch aussteht": "Τι εκκρεμεί",
    "Bilder": "Εικόνες",
    "Verantwortlich für die Vermittlung": "Υπεύθυνος για την υιοθεσία",
    "Bewerbungsformular": "Φόρμα αίτησης",
    "(öffnet in neuem Tab)": "(ανοίγει σε νέα καρτέλα)",
    "Vermittlungsverfahren": "Διαδικασία υιοθεσίας",
    "Vereinsangaben": "Στοιχεία συλλόγου",
    "Registergericht: Amtsgericht Bochum": "Δικαστήριο μητρώου: Πρωτοδικείο Bochum",
    "Registernummer: VR 4939": "Αριθμός μητρώου: VR 4939",
    "deinem Leben": "τη ζωή σου",
    "passen?": ";",
    "Bewerbungsformular öffnen": "Ανοίξτε τη φόρμα αίτησης",
    "Zurück zu allen Katzen": "Επιστροφή σε όλες τις γάτες",
    "Alle Katzen": "Όλες οι γάτες",
    "© 2026 Margo Animal Care Initiative · Artemida, Griechenland":
        "© 2026 Margo Animal Care Initiative · Αρτέμιδα, Ελλάδα",
    "Vermittlungsverfahren ansehen": "Δείτε τη διαδικασία υιοθεσίας",
    "männlich": "αρσενικό",
    "weiblich": "θηλυκό",
    "Mischling": "ημίαιμη",
    "mittel": "μεσαίο",
    "klein": "μικρό",
    "gross": "μεγάλο",
}
